apiVersion: v1
kind: Service
metadata:
  name: streaming-demo-encoder
spec:
  selector:
    app: streaming-demo
    component: video-encoder
  ports:
    - name: nfs
      port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: streaming-demo-encoder
  labels:
    app: streaming-demo
    component: video-encoder
spec:
  selector:
    matchLabels:
      app: streaming-demo
      component: video-encoder
  template:
    metadata:
      labels:
        app: streaming-demo
        component: video-encoder
    spec:
      containers:
        - name: dash-encoder
          image: mattiacattarinussi/streaming-demo-encoder
          volumeMounts:
            - mountPath: /stream
              name: stream
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /usr/share/nginx/html/
              name: stream
      volumes:
        - name: stream
          emptyDir: {}